--Check Table
SELECT *
FROM PortfolioProjectSuperstore..supersales
ORDER BY 1

--Check for null data
SELECT *
FROM PortfolioProjectSuperstore..supersales
WHERE [Row ID] IS NULL OR [Order ID] IS NULL OR [Order Date] IS NULL OR [Ship Date] IS NULL 
OR [Ship Mode] IS NULL OR  [Customer ID] IS NULL OR [Customer Name] IS NULL OR [Segment] IS NULL 
OR [Country] IS NULL OR [City] IS NULL OR [State] IS NULL OR [Postal Code] IS NULL OR [Region] IS NULL 
OR [Product ID] IS NULL OR [Category] IS NULL OR [Sub-Category] IS NULL OR [Product Name] IS NULL OR [Sales] IS NULL

--11 rows of Postal_Code were null
SELECT *
FROM PortfolioProjectSuperstore..supersales
WHERE [Postal Code] IS NULL

--Notice that postal code is null only for Burlington City, Vermont
--Need to fill the postal code of that city

UPDATE PortfolioProjectSuperstore..supersales
SET [Postal Code] = 5401
WHERE [City] = 'Burlington' AND [State] = 'Vermont'

SELECT *
FROM PortfolioProjectSuperstore..supersales
WHERE [City] = 'Burlington' AND [State] = 'Vermont'

--The dateset covers from 1st Jan 2015 to 30th Dec 2018 with 9800 transactions
SELECT MIN([Order Date]) AS min_orderdate, MAX([Order Date]) AS max_orderdate
FROM PortfolioProjectSuperstore..supersales

SELECT COUNT(1) AS [No. of Transactions]
FROM PortfolioProjectSuperstore..supersales

--Date with the most number of transactions
SELECT TOP 10 [Order Date], COUNT(1) AS Sales_Count, ROUND(SUM([Sales]), 2) AS Sales_Sum
FROM PortfolioProjectSuperstore..supersales
GROUP BY [Order Date]
ORDER BY Sales_Count DESC

--Most valuable customers for the company
SELECT TOP 5 [Customer Name], ROUND(SUM([Sales]), 2) AS Revenue
FROM PortfolioProjectSuperstore..supersales
GROUP BY [Customer Name]
ORDER BY 2 DESC

---Plot Table MOST VALUABLE CUSTOMERS 2015-2019

--States by revenue generated
SELECT [State], ROUND(SUM([Sales]), 2) AS Revenue
FROM PortfolioProjectSuperstore..supersales
GROUP BY [State]
ORDER BY 2 DESC

--Plot Choropleth Map

--Top 20 cities by average price per sales
SELECT TOP 20 [City], AVG(Sales) AS Sales_Avg, COUNT(1) AS Sales_Count
FROM PortfolioProjectSuperstore..supersales
GROUP BY [City]
ORDER BY Sales_Avg DESC

--Revenue generated by Category, Sub-Category
SELECT [Category] = ISNULL([Category], 'Total'), ROUND(SUM([Sales]), 2) AS Revenue
FROM PortfolioProjectSuperstore..supersales
GROUP BY [Category] WITH ROLLUP

SELECT [Category], [Sub-Category], ROUND(SUM([Sales]), 2) AS Revenue
FROM PortfolioProjectSuperstore..supersales
GROUP BY [Category], [Sub-Category]
ORDER BY 1

---Plot Pie Chart

--Annual revenue by region
SELECT YEAR([Order Date]) AS Year, [Region], ROUND(SUM([Sales]), 2) AS Revenue
FROM PortfolioProjectSuperstore..supersales
GROUP BY YEAR([Order Date]), Region
ORDER BY 1

---Plot Stacked Bar Chart

--Number of sales yearly
SELECT YEAR([Order Date]) AS Year, COUNT(1) AS Sales_Count, SUM(Sales) AS Sales_Sum
FROM PortfolioProjectSuperstore..supersales
GROUP BY YEAR([Order Date])
ORDER BY Sales_Count

--Revenue by Segment, Ship Mode
SELECT [Segment], ROUND(SUM([Sales]), 2) AS Revenue
FROM PortfolioProjectSuperstore..supersales
GROUP BY [Segment]
ORDER BY 2

SELECT [Ship Mode], ROUND(SUM([Sales]), 2) AS Revenue
FROM PortfolioProjectSuperstore..supersales
GROUP BY [Ship Mode]
ORDER BY 2

